version: '3.7'

services:
  postgresql:
    image: bitnami/postgresql:latest
    environment:
      POSTGRESQL_DATABASE: odoo
      POSTGRESQL_USERNAME: odoo
      POSTGRESQL_PASSWORD: odoo
    volumes:
      - postgresql_data:/bitnami/postgresql

  odoo:
    image: bitnami/odoo:latest
    environment:
      ODOO_DATABASE_HOST: postgresql
      ODOO_DATABASE_PORT_NUMBER: 5432
      ODOO_DATABASE_NAME: odoo
      ODOO_DATABASE_USER: odoo
      ODOO_DATABASE_PASSWORD: odoo
    ports:
      - "8069:8069"
    depends_on:
      - postgresql
    volumes:
      - odoo_data:/bitnami/odoo

volumes:
  postgresql_data:
  odoo_data: