name: Run Every 5 Minutes on Develop

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main  # Checks out the `main` branch

    - name: Run a script
      run: echo "This job runs every 5 minutes on the develop branch"