name: Run Every 5 Minutes on Develop

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: develop  # Checks out the `develop` branch

    - name: Run a script
      run: |
        echo "Content of example.txt:"
        cat example.txt