name: CI Pipeline

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
      - "test/**"
  pull_request:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.29.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          echo "Docker installed"
          sudo chmod +x /usr/local/bin/docker-compose
          echo "runnable"
          docker-compose version

      # Start Odoo using docker-compose
      - name: Start Odoo services
        run: docker-compose up -d

      # Wait for Odoo to be fully up
      - name: Wait for Odoo to start
        run: |
          while ! curl --silent --fail http://localhost:8069; do
            echo "Waiting for Odoo to start..."
            sleep 5
          done

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests
      - name: Run tests
        run: pytest