name: Run SeleniumBase Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Docker Compose
        if: always()
        run: |
          # Install docker-compose
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.29.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose          
          echo "Docker installed"
          sudo chmod +x /usr/local/bin/docker-compose
          echo "runnable"
          docker-compose version

      - name: Start Odoo
        run: |
          docker-compose up -d
          sleep 30  # Wait for Odoo to start

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver

      - name: Run SeleniumBase tests
        run: |
          export PATH=$PATH:/usr/lib/chromium-browser/
          pytest tests/ --browser=chrome --headless

      - name: Stop Docker Compose
        if: always()
        run: docker-compose down